import Head from 'next/head'
import {useState} from "react";
import axios from "axios";
import UploadFile from "@/components/UploadFile";

export default function Home() {
 const [to, setTo] = useState('');
 const [subject, setSubject] = useState('');
 const [message, setMessage] = useState('');
const [uploadImage, setUploadImage] = useState('');
 const sendMail = () => {
  if (to !== '' || subject !== '' || message !== '' || uploadImage !== null) {
  // axios.post('http://localhost:5000/sendMail', {
  //  to: to,
  //  subject: subject,
  //  message: message,
  //  file: uploadImage
  // }).then(res => {
  //  setTo('')
  //  setSubject('')
  //  setMessage('')
  //  setUploadImage(null)
  // }).catch(err => {
  //  console.log(err)
  // })
   var data = JSON.stringify({
    "to": to,
    "subject":subject,
    "text": message,
    "file": uploadImage
   });

   var config = {
    method: 'post',
    url: 'http://localhost:5000/sendMail',
    headers: {
     'Content-Type': 'application/json',
     'access-control-allow-origin': '*'
    },
    data : data
   };

   axios(config)
    .then(function (response) {
     setTo('')
     setSubject('')
     setMessage('')
     setUploadImage(null)
     alert('Mail başarıyla gönderildi.')
     console.log(JSON.stringify(response.data));
    })
    .catch(function (error) {
     console.log(error);
    });

  } else {
   alert('Tüm alanların doldurulması zorunludur.')
  }
 }
 return (
  <>
   <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="icon" href="/favicon.ico"/>
   </Head>
   <main className="bg-slate-800 min-h-screen">
    <div className='w-full h-full flex flex-col items-center justify-center gap-4 text-white pt-20'>
     <span className='text-xl font-bold'>MAIL SENDER</span>
     <div className='flex flex-col items-center justify-center gap-2'>
      <span className='font-bold'>TO</span>
      <input type="email" placeholder='example@gmail.com'
             className="text-center rounded-md text-slate-900 w-[300px] h-[30px] cursor-text outline-none focus:ring-1 focus:ring-[#ff6a6a]"
             onChange={(e) => {
              setTo(e.target.value)
             }}
             value={to}
      />

     </div>
     <div className='flex flex-col items-center justify-center gap-2'>
      <span className='font-bold'>SUBJECT</span>
      <input type="text" placeholder=' Message Subject'
             className="text-center rounded-md text-slate-900 w-[300px] h-[30px] cursor-text outline-none focus:ring-1 focus:ring-[#ff6a6a]"
             onChange={(e) => {
              setSubject(e.target.value)
             }}
             value={subject}
      />
     </div>
     <div className='flex flex-col items-center justify-center gap-2'>
      <span className='font-bold'>Message Text</span>
      <textarea placeholder=' Message Subject'
                className="text-center rounded-md text-slate-900 p-2 w-[300px] h-[130px] cursor-text outline-none focus:ring-1 focus:ring-[#ff6a6a]"
                onChange={(e) => {
                 setMessage(e.target.value)
                }}
                value={message}
      />

     </div>
     <div className='flex flex-col w-[300px]  items-center justify-center gap-2'>
     <UploadFile uploadImage={uploadImage} setUploadImage={setUploadImage} />
     </div>

     <button className='bg-[#ff6a6a] text-white rounded-md w-[200px] h-[30px]'
             onClick={() => sendMail()}>
      <span className='font-bold'>SEND</span>
     </button>

    </div>
   </main>
  </>
 )
}
